# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wojciech Pelczar Blog
email: wpelczar1@gmail.com
description: Programming Blog by Wojciech Pelczar
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wpelczar.com" # the base hostname & protocol for your site
github_username:  wpelczar
permalink: pretty
rss: "http://wpelczar.com/feed.xml"
disqus_shortname: wpelczar-blog
google_analytics: UA-85733142-1
paginate: 5
paginate_path: "page:num"
# Build settings
markdown: kramdown
kramdown:
  input: GFM
exclude: [ "typings",
  "typings.json",
  "jsconfig.json",
  "package.json",
  "node_modules",
  "gulpfile.js"
]
gems:
  - jekyll-paginate